Corrected TLE deserializer for mean motion field <10
BatchDrake/suscan pull request #63
Opened 2023-01-25 15:10 UTC by arf20

Rather silly fix, but it apparently works. Please do try it yourself, and correct me.

2023-01-25 16:38 UTC, arf20 commented
Soapy still broken on macos, lol

2023-01-25 16:44 UTC, BatchDrake requested changes

2023-01-25 16:44 UTC, BatchDrake commented on sgdp4/tle.c
> +        linebuf[52] != ' ' ? "%1u %05u %8lf %8lf %07u %8lf %8lf %11lf%5[0-9 ]%1u" :
This looks a bit too rigged up to my taste. We should focus on providing a sscanf format that does the work right and, if it was not possible, unpack the values in a different way.

2023-01-25 16:44 UTC, BatchDrake commented on sgdp4/tle.c
> +        linebuf[52] != ' ' ? "%1u %05u %8lf %8lf %07u %8lf %8lf %11lf%5[0-9 ]%1u" :
Also this may crash if `strlen(linebuf) <= 52`

2023-03-20 00:02 UTC, arf20 commented
Added debian packages to CI workflow

2023-03-25 17:05 UTC, BatchDrake approved these changes

2023-03-25 17:06 UTC, merged